[project]
name = "dagon"
version = "0.11.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "vector-of-bool", email = "vectorofbool@gmail.com" }]
requires-python = ">=3.13"
dependencies = []
classifiers = ["Private :: Do not upload"]

[tool.uv.build-backend]
namespace = true
source-exclude = ["**/*_test.py"]

[[tool.uv.index]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[project.scripts]
dagon = "dagon:main"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"


[dependency-groups]
dev = [
    "pyright>=1.1.405",
    "pytest>=8.4.2",
    "pytest-xdist>=3.8.0",
    "ruff>=0.12.12",
]

[tool.pyright]
include = ["dagon/"]
strict = ["**"]
# typeshed-path = "typings"
pythonversion = "3.13"

[tool.ruff]
line-length = 120
